
REGIONS = {
    "1": "Valle d'Aosta",
    "2": "Piemonte",
    "3": "Liguria",
    "4": "Lombardia",
    "5": "Trentino-Alto Adige",
    "6": "Veneto",
    "7": "Friuli-Venezia Giulia",
    "8": "Emilia-Romagna",
    "9": "Toscana",
    "10": "Umbria",
    "11": "Lazio",
    "12": "Marche",
    "13": "Abruzzo",
    "14": "Molise",
    "15": "Campania",
    "16": "Puglia",
    "17": "Basilicata",
    "18": "Calabria",
    "19": "Sardegna",
    "20": "Sicilia",
}

CATEGORIES = {
    "1": "MOTORI",
    "2": "Auto",
    "3": "Moto e Scooter",
    "4": "Veicoli commerciali",
    "5": "Accessori Auto",
    "6": "IMMOBILI",
    "7": "Appartamenti",
    "8": "Uffici e Locali commerciali",
    "9": "ELETTRONICA",
    "10": "Informatica",
    "11": "Audio/Video",
    "12": "Telefonia",
    "13": "PER LA CASA e LA PERSONA",
    "14": "Arredamento e Casalinghi",
    "15": "Giardino e Fai da te",
    "16": "Abbigliamento e Accessori",
    "17": "Tutto per i bambini",
    "18": "SPORTS E HOBBY",
    "19": "Musica e Film",
    "20": "Sports",
    "21": "Collezionismo",
    "22": "Nautica",
    "23": "Animali",
    "24": "LAVORO E SERVIZI",
    "25": "Attrezzature di lavoro",
    "26": "Offerte di lavoro",
    "27": "ALTRI ANNUNCI",
    "28": "Altri",
    "29": "Ville singole e a schiera",
    "30": "Terreni e rustici",
    "31": "Garage e box",
    "32": "Loft, mansarde e altro",
    "33": "Case vacanza",
    "34": "Caravan e Camper"
}